# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arma_crossprod <- function(A, B) {
    .Call(`_besiw_arma_crossprod`, A, B)
}

arma_tcrossprod <- function(A, B) {
    .Call(`_besiw_arma_tcrossprod`, A, B)
}

arma_matmul <- function(A, B) {
    .Call(`_besiw_arma_matmul`, A, B)
}

arma_matsum <- function(A, B) {
    .Call(`_besiw_arma_matsum`, A, B)
}

arma_dmvnorm <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_besiw_arma_dmvnorm`, x, mean, sigma, logd)
}

transform_cov <- function(p, Lambda, Gamma) {
    .Call(`_besiw_transform_cov`, p, Lambda, Gamma)
}

splitList <- function(L) {
    .Call(`_besiw_splitList`, L)
}

eig_decomp <- function(A) {
    .Call(`_besiw_eig_decomp`, A)
}

is_pd <- function(A) {
    .Call(`_besiw_is_pd`, A)
}

gSIW_sampling <- function(Gamma_init, eigval_H_0, eigvec_H_0, r_vec, k, iter, burnin, thin, progress = TRUE) {
    .Call(`_besiw_gSIW_sampling`, Gamma_init, eigval_H_0, eigvec_H_0, r_vec, k, iter, burnin, thin, progress)
}

